---
- hosts: all
  become: true
  pre_tasks:

  - name: Update repository index (CentOS)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: CentOS
  become: true
  roles:
    - enterprise
    - monitoring
    - banner
